# Generated by Django 2.2.12 on 2020-08-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='coment',
            field=models.TextField(default=''),
        ),
    ]
